name: Postman collection tests using Newman
on:
  push:
    branches:
    - master
    - staging
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install -g newman
      - run: newman run NimbleHerokuAppDemo.postman_collection.json --environment NimbleHerokuAppDemo.postman_environment.json
